apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simples
  labels:
    name: ingress-simples
spec:
  IngressClassName: nginx
  rules:
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-green
            port: 
              number: 80