apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: registry.k8s.io/busybox
        command: 
          - /bin/sh
        args:
          - -c
          - touch /temp/ready; sleep 30; rm -f /temp/ready; sleep 600;
        ports:
        - containerPort: 3000
        readinessProbe: 
          exec:
            command:
              - cat
              - /tmp/ready
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000