# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: recurso-computacional
# spec:
#   hard:
#     requests.cpu: "1"
#     requests.memory: "1Gi"
#     limits.cpu: "2"
#     limits.memory: "2Gi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: contador-objetos
spec:
  hard:
    pods: "4"
    services: "2"
    secrets: "3"
    configmaps: "4"
    services.loadbalancers: "2"
    count/deployments.app: "2"
    count/replicaset.app: "2"