# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: valor-padrao
# spec:
#   limits:
#     - type: Container
#       default: # Resource limits
#         cpu: 500m
#         memory: 64M
#       defaultRequest: # Resource request
#         cpu: 250m
#         memory: 32m
---      
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-pod
spec:
  limits:
    - type: Pod
      max:
        memory: 512M
        cpu: 250m
      min:
        memory: 250M
        cpu: 100m