apiVersion: v1
kind: PersistenceVolume
metadata:
  name: pv0003
  labels: nfs-manual
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistenceVolumeReclaimPolicy: Delete
  volumeMode: FileSystem
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2