name: Deploy Fake
on:
  workflow_call:
    secrets:
      environment:
        required: true
        description: "environment to deploy"
jobs:
  deploy-kubernets:
     runs-on: ubuntu-latest
     steps:
       - name: Deploy no ambiente
         run: echo "Executando o deploy no ambiente de ${{ secrets.environment }}"
       - name: Curl Deploy No Ambiente
         run: "curls -X POST https://webhook.site/6b535984-09d9-415f-a2f0-81526aa2bbf8 -d '{ environment: ${{ secrets.environment }} }'"
