name: CI/CD Fake
on:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Image Docker
        run: acho "Execução do comando de docker build"
      - name: Execução de Testes de Software
        run: acho "Aqui eu executo o teste de software"
      - name: Publicando a Release
        run: echo "Publicação da Release Final"
  CD:
     runs-on: ubuntu-latest
     steps:
       - name: Deploy no ambiente
         run: acho "Executando o deploy no ambiente de desenvolvimento"
