name: CI/CD Fake
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        default: "dev"
        required: true
        description: "environment to deploy"
        options:
          - uat
          - rc
          - production
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Image Docker
        run: echo "Execução do comando de docker build"
      - name: Execução de Testes de Software
        run: echo "Aqui eu executo o teste de software"
      - name: Publicando a Release
        run: echo "Publicação da Release Final"
  CD:
    needs: [CI]
    uses: RafaelFerSilva/DevopsPro/.github/workflows/cd.yaml@main
    with:
      environment: ${{ inputs.environment }}
