name: Workflow Evento
on:
  pull_request:
    branches: ["main"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
        
      - name: Alteração no card
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Adicionando um comentário aqui sobre o PR'
            })
