name: Workflow Evento
on:
  push:
    branches: ["main", "feature/*", "release/*"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste
        run: echo "${{ inputs.exemplo-input }}"
